version: "3.9"
networks:
  demo:
    external: false
volumes:
  m2repo:
  gitea:
services:
  gitea:
    image: gitea/gitea:1.18.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://localhost:3000/
      - GITEA__server__DOMAIN=localhost
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__security__INSTALL_LOCK=true
    restart: always
    networks:
      - demo
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
  jenkins:
      container_name: jenkins
      networks:
        - demo
      build:
        context: .
      ports:
        - "8080:8080"
      volumes:
        - m2repo:/m2repo:rw
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
        interval: 5s
        timeout: 30s

